Add support for single-valued attributes in index specifications (#8199)
#### What type of PR is this?

/kind bug
/area core
/area plugin
/milestone 2.22.x

#### What this PR does / why we need it:

In PR <https://github.com/halo-dev/halo/pull/8187>, I restricted unsupported operations in MultiValueIndex, such as `between`, `stringContains`.

But defining an index spec with deprecated style will be converted to MultiValueIndex always, which results in some plugins to fail to work properly.

```java
java.lang.UnsupportedOperationException: Multi-value index does not support stringContains operation
	at run.halo.app.extension.index.MultiValueIndex.stringContains(MultiValueIndex.java:167) ~[main/:na]
```

This PR converts them into SingleValueIndex to brings them back to work.

#### Does this PR introduce a user-facing change?

```release-note
None
```