Fix recursive update issue in concurrent map for thumbnail generation (#7789)
#### What type of PR is this?

/kind bug
/area core
/milestone 2.22.x

#### What this PR does / why we need it:

This PR fixes recursive update issue in concurrent map for thumbnail generation.

```java
java.lang.IllegalStateException: Recursive update
	at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(Unknown Source) ~[na:na]
```

#### Does this PR introduce a user-facing change?

```release-note
None
```