Replace TemplateEngine with SpringTemplateEngine in ThumbnailImgTagPostProcessorTest (#7916)
#### What type of PR is this?

/kind bug
/are core
/milestone 2.22.x

#### What this PR does / why we need it:

This PR replaces TemplateEngine with SpringTemplateEngine in ThumbnailImgTagPostProcessorTest because ongl dependencies was removed by Thymeleaf Spring6.

If we don't include thymeleaf dependency manually, the unit test will fail as below:

```java
java.lang.NoClassDefFoundError: ognl/PropertyAccessor
	at org.thymeleaf.standard.StandardDialect.getVariableExpressionEvaluator(StandardDialect.java:178)
	at org.thymeleaf.standard.StandardDialect.getExecutionAttributes(StandardDialect.java:392)
	at org.thymeleaf.DialectSetConfiguration.build(DialectSetConfiguration.java:263)
	at org.thymeleaf.EngineConfiguration.<init>(EngineConfiguration.java:123)
	at org.thymeleaf.TemplateEngine.initialize(TemplateEngine.java:341)
	at org.thymeleaf.TemplateEngine.getConfiguration(TemplateEngine.java:411)
	at run.halo.app.core.attachment.thumbnail.ThumbnailImgTagPostProcessorTest.setUp(ThumbnailImgTagPostProcessorTest.java:42)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.ClassNotFoundException: ognl.PropertyAccessor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 10 more
```

> https://github.com/halo-dev/halo/actions/runs/19129978229/job/54668145618

#### Does this PR introduce a user-facing change?

```release-note
None
```